name: Edit New Issue Body

on:
  issues:
    types: [opened]

jobs:
  edit-issue-body:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Edit issue body
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const newBody = `${issue.body}`;
            const newBody1 = "";
            newBody.split('\n');
            for(let i=0; i<newBody.length; ++i){
                if(newBody[i].startsWith("### Screenshots") && i+2<newBody.length){
                    if(newBody[i+1] == "```bash" && newBody[i+2] == "```"){
                        newBody[i] = "_-1";
                        newBody[i+1] = "_-1";
                        newBody[i+2] = "_-1";
                    }
                }
                if(newBody[i] != "_-1"){
                    newBody1 += newBody[i] + '\n';
                }
            }

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: newBody1,
            });